name: CENTURI_Tessier_Microglia

channels:
  - conda-forge
      
dependencies:
  - python=3.9
  - pyqt=5.12.3
  - napari
  - numpy
  - scipy
  - scikit-image
  - matplotlib-base
  - joblib
  - pip
  - pip:
    - pystackreg
